### ISSUE TITLE
You should be accepting donations :)

### ISSUE THREAD

**Issue by sedulam** [damonhook/aos-statshammer#56]
Sorry for creating this as a bug ticket, but couldn't find another way to reach you. I think you should have some way of accepting donations. I would be happy to send a "beer" over your way.
Many thanks for such a beautifully crafted statistics helper for Warhammer!

**Comment by damonhook** [comment]
Thank you very much and I am glad you like the tool.

This is more of a project I work on when I have some free time, and was an opportunity to dive more heavily into react (which I don't get to do much at work). 

So at this time I haven't got any plans to add the ability for donations.

Once again I really appreciate the kind words

**Comment by sedulam** [comment]
Great usage of learning and getting your hands on new tech. I can relate to that. :) Keep up the awesome work!
