### ISSUE TITLE
Add a reverse cumulative damage probability

### ISSUE THREAD

**Issue by omomom666** [damonhook/aos-statshammer#64]
It would be more useful to have a cumulative probability of dealing of X amount of damage or more. Now it is so that the percentages tell the probability of dealing X amount of damage or less.

In my opinion it would be more logical to have value of the probability of dealing at least X amount of damage.

**Comment by damonhook** [comment]
I do agree with you, I am currently working on a larger refactor of the project, and in that release I have added the ability of inverting the cumulative probability graph.

It is still very much a WIP (it is a large refactor), but here is a sneak peak at what it currently looks like:

https://user-images.githubusercontent.com/35456894/109011802-f9fbfb00-76b9-11eb-8079-e4a6ef4a869a.mov

**Comment by omomom666** [comment]
Awesome! You've build great tool and sounds like it's going to be even better!
